sudo: false
language: scala
env:
  global:
  - secure: UOpiFIXrwDpaiHVZysy76zaZLiKJpdvK+0oGAeVN07nxjY4wKVTzZbIEywIG+QnIFFa98V5bhlh0u+1Jmi+8L7KnZiB0zbt0vWhkl/Dbcm5rWlRfpHyEVzY3cUY50XtWrIP362plvx07npbA3VBBGwkiy1CW6ZIj9KJQ3NlvOMw2RkEDZ/8TEJI8EWf7pd3S+9Jat/asLDOuzDgk0s+YuRQktv7oRtNbGpIWMy0c36oPdlfOrXpzk9ZfouJ3SJm4TU+gze4P1XIJFQOaMvQf5bIqjq3q3QIqrG2FVZOM7mVzBuVHJQ5OYH3cm1f66SwtI8SQQnDkp8DtTHc8k8tBEoM7UJo7APxjV135LGL+o5czLhGEkxgK8IdzLoDT+pzJzeZCK4+Wa+yx5ZfuzIHLuQR00KdRBnVJYK8UDeahgB36t2/dT5T5omXFcgW0FlPEPlNDlaTxLMJt7qMFap0mCabaOwR0KYn/r4MygddhZgXIv/53uVI/o8b+5XekAc0iauOXlZ5cXholNepgZS4Ik0wVXowz2fXRfPUU4BhMB/J06to+JnrfNfsIbAxmiNydoaK9pRenx64K84lMd54h70+sD4W2E/N6W/OFxoAnxTem4v1l93EMF4UxedOhxgpFNYaJySu1V5qbTCxyY/+Jj8v+vXwmaEvtdqHWafkUNMQ=
  - secure: zdWZ7egDwfdAEVicKhDT67rD6LFKIQkenzHm77phsXAZx9GcSg2KDWkqWbjLxFCqWsuVLOOlyFPd0zJd7lhr9SS6Rc2Oc+UKTFWkMUcKL7xfiWaAq/JibNLBHAfXC7QHNVD53Tu11WzHuYYTGmFqRgMQyWXwmRxHyCFYFUIu+4hT9MbhsdLGfnxMuJg1e/43HEEkoDfLWZyKk9W78n26+yczxnrZiGLACbgjI80G4oGylgnI3+HuSFKStqaClUUa1BMZujccegup6O8wSHmpQN/EAl/DuCpSDddw8WHTvxAoffoy4CmaeK4Hj/LU6NkSIgTjcptXPhd8qX51OpVOZ+ysbsPcN40HGJZrsWLi2+rNipyuYjAz0HSYA/lLbG42WwUVBmcgMP8UvPXzN7+sOne6w8BYQwq7sXO2abVZq3OLrazxlzehBPybnA4I3Twtq4R7nUbrnQPVkNDDINuft3WDXTWxlx8eqL9LdXlHBnR/efdliA9kKbopGpzIGh7riDaT6D/hJ1OW+pLZw7xhnKTuBitelk2cTXh8QZ1eLW6dZ7reFbGFC3WEkY54wNCuJ5z60VJi/lWzmcTB9r/qN76fohrqDv97okpI+NLrDKXiSQygD4ZUsERQ88OkMfcJ2iY410pa0ZrsD85hpYMOXutoHCv2sx1SB0EvrcvFHA0=
jdk:
- openjdk8
- oraclejdk8
scala:
- 2.11.8
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
script:
- ".travis/build-and-test.sh"
deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: geotrellis/maml
after_deploy:
- rm -f "${HOME}/.bintray/.credentials"
