sudo: false
language: scala
jdk:
- openjdk8
- oraclejdk8
scala:
- 2.11.8
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
script:
- ".travis/build-and-test.sh"
deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: geotrellis/maml
after_deploy:
- rm -f "${HOME}/.bintray/.credentials"
